"""
Day 28 - Recruiter Report Formatter

Converts a structured screening report into a
human-readable recruiter report.
"""

import json

from .report_schema import ScreeningReport


class ScreeningReportFormatter:

    def to_text(self, report: ScreeningReport) -> str:
        lines = []

        lines.append("=" * 70)
        lines.append("              ZECPATH AI - SCREENING REPORT")
        lines.append("=" * 70)

        lines.append("")
        lines.append("CANDIDATE")
        lines.append("-" * 70)
        lines.append(f"Candidate ID : {report.candidate_id}")
        lines.append(f"Name         : {report.candidate_name}")
        lines.append(f"Status       : {report.screening_status}")

        lines.append("")
        lines.append("KEY ANSWERS")
        lines.append("-" * 70)

        if report.key_answers:
            for key, value in report.key_answers.items():
                label = key.replace("_", " ").title()
                lines.append(f"{label}: {value}")
        else:
            lines.append("No key answers available.")

        lines.append("")
        lines.append("CONFIRMED SKILLS")
        lines.append("-" * 70)

        if report.confirmed_skills:
            for skill in report.confirmed_skills:
                lines.append(f"- {skill}")
        else:
            lines.append("- None confirmed")

        lines.append("")
        lines.append("SALARY EXPECTATION")
        lines.append("-" * 70)
        lines.append(
            report.salary_expectation
            if report.salary_expectation
            else "Not provided"
        )

        lines.append("")
        lines.append("AVAILABILITY")
        lines.append("-" * 70)
        lines.append(
            report.availability
            if report.availability
            else "Not provided"
        )

        lines.append("")
        lines.append("STRENGTHS")
        lines.append("-" * 70)

        if report.strengths:
            for item in report.strengths:
                lines.append(f"+ {item}")
        else:
            lines.append("- None identified")

        lines.append("")
        lines.append("RISKS")
        lines.append("-" * 70)

        if report.risks:
            for item in report.risks:
                lines.append(f"! {item}")
        else:
            lines.append("- None identified")

        lines.append("")
        lines.append("MISSING DATA")
        lines.append("-" * 70)

        if report.missing_data:
            for item in report.missing_data:
                lines.append(f"? {item}")
        else:
            lines.append("- No missing data identified")

        lines.append("")
        lines.append("=" * 70)
        lines.append("Generated by Zecpath AI")
        lines.append("=" * 70)

        return "\n".join(lines)

    def to_json(self, report: ScreeningReport) -> str:
        return json.dumps(
            report.to_dict(),
            indent=2,
            ensure_ascii=False,
        )